// ANIME EBOOKS / LIGHT NOVELS ONLY — NO MANGA
const animeData = [
    {id:1,title:"Demon Slayer: The Flower of Happiness",titleTl:"Demon Slayer: Bulaklak ng Kaligayahan",year:"2019",type:"Light Novel",lang:"EN / TL",category:["trending","all"],desc:"Official light novel side story following Tanjiro and the Demon Slayer Corps on a new mission.",descTl:"Opisyal na karagdagang kwento tungkol sa misyon ni Tanjiro at ng mga Pamatay-Demonyo.",img:"https://upload.wikimedia.org/wikipedia/en/0/09/Kimetsu_no_Yaiba_vol_1.jpg",link:"#"},
    {id:2,title:"Jujutsu Kaisen: Summer of Ashes, Autumn of Dust",titleTl:"Jujutsu Kaisen: Tag-init ng Abo, Taglagas ng Alikabok",year:"2019",type:"Light Novel",lang:"EN / TL",category:["trending","new","all"],desc:"Original light novel exploring missions and backstories of Yuji, Megumi, and Nobara.",descTl:"Orihinal na nobela tungkol sa mga misyon at nakaraan nina Yuji, Megumi, at Nobara.",img:"https://upload.wikimedia.org/wikipedia/en/9/91/Jujutsu_Kaisen_vol_1.jpg",link:"#"},
    {id:3,title:"One Piece: The Novel",titleTl:"One Piece: Ang Nobela",year:"2000",type:"Light Novel",lang:"EN / TL",category:["trending","all"],desc:"Written novel retelling of the early adventures of Luffy and his crew.",descTl:"Isinalaysay sa nobela ang mga unang pakikipagsapalaran ni Luffy at ng kanyang mga kasama.",img:"https://upload.wikimedia.org/wikipedia/en/6/60/One_Piece_vol_1.jpg",link:"#"},
    {id:4,title:"Solo Leveling: Light Novel Complete",titleTl:"Solo Leveling: Kumpletong Nobela",year:"2016",type:"Light Novel",lang:"EN / TL",category:["new","all"],desc:"The original full light novel series that inspired the manhwa adaptation.",descTl:"Ang orihinal na buong nobela na naging batayan ng sikat na kwento.",img:"https://upload.wikimedia.org/wikipedia/en/7/7f/Solo_Leveling_vol_1.jpg",link:"#"},
    {id:5,title:"Attack on Titan: Before the Fall",titleTl:"Pag-atake ng Higante: Bago ang Pagbagsak",year:"2011",type:"Light Novel",lang:"EN / TL",category:["all"],desc:"Prequel light novel set decades before Eren Yeager’s story begins.",descTl:"Kwento bago pa man ipinanganak si Eren Yeager.",img:"https://upload.wikimedia.org/wikipedia/en/d/d6/Shingeki_no_Kyojin_vol_1.jpg",link:"#"},
    {id:6,title:"Spy x Family: Family Portrait",titleTl:"Spy x Family: Larawan ng Pamilya",year:"2021",type:"Light Novel",lang:"EN / TL",category:["trending","new","all"],desc:"Original light novel with extra missions and funny daily life of the Forgers.",descTl:"Karagdagang kwento at masasayang karanasan ng pamilya Forger.",img:"https://upload.wikimedia.org/wikipedia/en/1/19/Spy_x_Family_vol_1.jpg",link:"#"},
    {id:7,title:"Naruto: The Chronicles",titleTl:"Naruto: Ang mga Kasaysayan",year:"2002",type:"Light Novel",lang:"EN / TL",category:["trending","all"],desc:"Official light novels expanding Naruto’s world, missions, and character backstories.",descTl:"Opisyal na nobela tungkol sa mundo at mga misyon ni Naruto.",img:"https://upload.wikimedia.org/wikipedia/en/9/94/Naruto_vol_1.jpg",link:"#"},
    {id:8,title:"Bleach: The Death Save the Strawberry",titleTl:"Bleach: Ang Kaligtasan ng Prutas",year:"2012",type:"Light Novel",lang:"EN / TL",category:["all"],desc:"Light novel telling Ichigo’s untold story between key battles.",descTl:"Kwento ni Ichigo na hindi nakita sa pangunahing kwento.",img:"https://upload.wikimedia.org/wikipedia/en/7/72/Bleach_vol_1.jpg",link:"#"},
    {id:9,title:"My Hero Academia: School Briefs",titleTl:"Ang Aking Bayani: Mga Kwento sa Paaralan",year:"2016",type:"Light Novel",lang:"EN / TL",category:["trending","all"],desc:"Light novel series showing daily life, training, and events at U.A. High School.",descTl:"Mga kwento ng pang-araw-araw na buhay at pagsasanay sa U.A. High.",img:"https://upload.wikimedia.org/wikipedia/en/6/6a/My_Hero_Academia_vol_1.jpg",link:"#"},
    {id:10,title:"Tokyo Ghoul: Days",titleTl:"Halimaw ng Tokyo: Mga Araw",year:"2013",type:"Light Novel",lang:"EN / TL",category:["all"],desc:"Light novel collection of side stories and everyday moments from the series.",descTl:"Mga karagdagang kwento at karanasan sa mundo ng Tokyo Ghoul.",img:"https://upload.wikimedia.org/wikipedia/en/e/e5/Tokyo_Ghoul_vol_1.jpg",link:"#"},
    {id:11,title:"Death Note: Another Note",titleTl:"Aklat ng Kamatayan: Isa pang Tala",year:"2006",type:"Light Novel",lang:"EN / TL",category:["all"],desc:"Prequel light novel about the Los Angeles BB Murder Cases before Kira.",descTl:"Kwento ng mga pagpatay sa Los Angeles bago pa man dumating si Kira.",img:"https://upload.wikimedia.org/wikipedia/en/6/64/Death_Note_vol_1.jpg",link:"#"},
    {id:12,title:"Black Clover: The Knights of the Kingdom",titleTl:"Itim na Klaber: Mga Kawal ng Kaharian",year:"2018",type:"Light Novel",lang:"EN / TL",category:["new","all"],desc:"Official light novel focusing on the magic knights and their missions.",descTl:"Opisyal na nobela tungkol sa mga kawal ng mahika at kanilang mga misyon.",img:"https://upload.wikimedia.org/wikipedia/en/6/69/Black_Clover_vol_1.jpg",link:"#"},
    {id:13,title:"Re:Zero - Starting Life in Another World",titleTl:"Re:Zero - Magsimula Muli sa Ibang Mundo",year:"2014",type:"Light Novel",lang:"EN / TL",category:["all"],desc:"Complete original light novel series where Subaru returns from death repeatedly.",descTl:"Ang buong orihinal na nobela kung saan paulit-ulit na bumabalik si Subaru mula sa kamatayan.",img:"https://upload.wikimedia.org/wikipedia/en/7/7c/Re-Zero_vol_1.jpg",link:"#"},
    {id:14,title:"Overlord",titleTl:"Overlord",year:"2012",type:"Light Novel",lang:"EN / TL",category:["all"],desc:"Original light novel about a gamer ruling a fantasy world as an undead overlord.",descTl:"Orihinal na nobela tungkol sa manlalaro na namuno sa mundong pantasya bilang isang hari.",img:"https://upload.wikimedia.org/wikipedia/en/6/6d/Overlord_vol_1.jpg",link:"#"},
    {id:15,title:"Konosuba: God's Blessing on This Wonderful World",titleTl:"Konosuba: Pagpapala sa Kahanga-hangang Mundong Ito",year:"2013",type:"Light Novel",lang:"EN / TL",category:["all"],desc:"Comedy light novel about a boy reborn with a useless goddess.",descTl:"Nakakatawang nobela tungkol sa batang isinilang muli kasama ang walang silbing diyosa.",img:"https://upload.wikimedia.org/wikipedia/en/e/e7/Konosuba_vol_1.jpg",link:"#"},
    {id:16,title:"Sword Art Online",titleTl:"Sword Art Online",year:"2009",type:"Light Novel",lang:"EN / TL",category:["all"],desc:"Original light novel series where players are trapped inside a VR game.",descTl:"Ang orihinal na nobela kung saan naipit ang mga manlalaro sa loob ng laro.",img:"https://upload.wikimedia.org/wikipedia/en/6/6b/Sword_Art_Online_vol_1.jpg",link:"#"},
    {id:17,title:"No Game No Life",titleTl:"Walang Laro Walang Buhay",year:"2012",type:"Light Novel",lang:"EN / TL",category:["all"],desc:"Light novel about genius siblings who rule a world decided by games.",descTl:"Nobela tungkol sa magkapatid na namuno sa mundong nakadepende sa laro.",img:"https://upload.wikimedia.org/wikipedia/en/6/6e/No_Game_No_Life_vol_1.jpg",link:"#"},
    {id:18,title:"Fate/Stay Night",titleTl:"Fate/Stay Night",year:"2004",type:"Light Novel",lang:"EN / TL",category:["all"],desc:"Original light novel about mages fighting for the Holy Grail.",descTl:"Orihinal na nobela tungkol sa labanan para sa Banal na Kopa.",img:"https://upload.wikimedia.org/wikipedia/en/9/92/Fate_stay_night_vol_1.jpg",link:"#"},
    {id:19,title:"Chainsaw Man: Buddy Stories",titleTl:"Tao na Lagari: Mga Kwento ng Magkaibigan",year:"2021",type:"Light Novel",lang:"EN / TL",category:["trending","new","all"],desc:"Official light novel side stories focusing on Denji, Power, and Aki.",descTl:"Opisyal na nobela tungkol sa pagkakaibigan nina Denji, Power, at Aki.",img:"https://upload.wikimedia.org/wikipedia/en/8/8b/Chainsaw_Man_vol_1.jpg",link:"#"},
    {id:20,title:"Hunter x Hunter: The Journey",titleTl:"Mangangaso x Mangangaso: Ang Paglalakbay",year:"2001",type:"Light Novel",lang:"EN / TL",category:["trending","all"],desc:"Light novel expanding the adventures of Gon and his friends.",descTl:"Karagdagang nobela tungkol sa paglalakbay ni Gon at ng kanyang mga kaibigan.",img:"https://upload.wikimedia.org/wikipedia/en/9/94/Hunter_x_Hunter_vol_1.jpg",link:"#"},
    {id:21,title:"Fullmetal Alchemist: The Land of Sand",titleTl:"Buong Metal na Alkemista: Lupain ng Buhangin",year:"2003",type:"Light Novel",lang:"EN / TL",category:["all"],desc:"Official light novel side story from the Fullmetal universe.",descTl:"Opisyal na karagdagang kwento mula sa mundo ng Alchemist.",img:"https://upload.wikimedia.org/wikipedia/en/9/9d/Fullmetal_Alchemist_vol_1.jpg",link:"#"},
    {id:22,title:"Dragon Ball: The Legend",titleTl:"Dragon Ball: Ang Alamat",year:"1986",type:"Light Novel",lang:"EN / TL",category:["trending","all"],desc:"Written novel retelling the early adventures of Goku.",descTl:"Isinalaysay sa nobela ang mga unang pakikipagsapalaran ni Goku.",img:"https://upload.wikimedia.org/wikipedia/en/c/c9/Dragon_Ball_vol_1.jpg",link:"#"},
    {id:23,title:"Your Name. Light Novel",titleTl:"Ang Iyong Pangalan. Nobela",year:"2016",type:"Light Novel",lang:"EN / TL",category:["all"],desc:"Original light novel adaptation of the hit movie by Makoto Shinkai.",descTl:"Orihinal na nobela ng sikat na pelikula ni Makoto Shinkai.",img:"https://upload.wikimedia.org/wikipedia/en/8/85/Your_Name_novel.jpg",link:"#"},
    {id:24,title:"Weathering With You Light Novel",titleTl:"Pagbabago ng Panahon Nobela",year:"2019",type:"Light Novel",lang:"EN / TL",category:["new","all"],desc:"Light novel adaptation of the film about a girl who controls the weather.",descTl:"Nobela ng kwento tungkol sa batang babae na kumokontrol sa panahon.",img:"https://upload.wikimedia.org/wikipedia/en/6/66/Weathering_With_You_novel.jpg",link:"#"},
    {id:25,title:"Tokyo Revengers: A Letter from Keisuke Baji",titleTl:"Mga Tagapaghiganti ng Tokyo: Liham mula kay Baji",year:"2021",type:"Light Novel",lang:"EN / TL",category:["trending","all"],desc:"Official light novel focusing on Baji’s past and loyalty.",descTl:"Opisyal na nobela tungkol sa nakaraan at katapatan ni Baji.",img:"https://upload.wikimedia.org/wikipedia/en/7/7d/Tokyo_Revengers_vol_1.jpg",link:"#"},
    {id:26,title:"Violet Evergarden",titleTl:"Violet Evergarden",year:"2015",type:"Light Novel",lang:"EN / TL",category:["all"],desc:"Award-winning original light novel about a former soldier learning to write letters.",descTl:"Tanyag na nobela tungkol sa dating sundalo na natutong magsulat ng liham.",img:"https://upload.wikimedia.org/wikipedia/en/7/7b/Violet_Evergarden_vol_1.jpg",link:"#"},
    {id:27,title:"Steins;Gate",titleTl:"Steins;Gate",year:"2009",type:"Light Novel",lang:"EN / TL",category:["all"],desc:"Original light novel about time travel and changing fate.",descTl:"Orihinal na nobela tungkol sa paglalakbay sa oras at pagbabago ng tadhana.",img:"https://upload.wikimedia.org/wikipedia/en/7/73/Steins_Gate_vol_1.jpg",link:"#"},
    {id:28,title:"The Seven Deadly Sins: Seven Days",titleTl:"Ang Pitong Nakamamatay na Kasalanan: Pitong Araw",year:"2014",type:"Light Novel",lang:"EN / TL",category:["all"],desc:"Light novel side story expanding the world of the Seven Deadly Sins.",descTl:"Karagdagang nobela tungkol sa mundo ng pitong kasalanan.",img:"https://upload.wikimedia.org/wikipedia/en/9/9c/The_Seven_Deadly_Sins_vol_1.jpg",link:"#"},
    {id:29,title:"Fairy Tail: The Phoenix Priestess",titleTl:"Buntot ng Diwata: Ang Pari ng Ibong Adarna",year:"2012",type:"Light Novel",lang:"EN / TL",category:["all"],desc:"Light novel based on the official movie story.",descTl:"Nobela batay sa opisyal na kwento ng pelikula.",img:"https://upload.wikimedia.org/wikipedia/en/0/06/Fairy_Tail_vol_1.jpg",link:"#"},
    {id:30,title:"One Punch Man: A Hero Nobody Knows",titleTl:"Isang Suntok na Tao: Bayaning Walang Nakakakilala",year:"2015",type:"Light Novel",lang:"EN / TL",category:["trending","all"],desc:"Official light novel exploring Saitama’s daily life and battles.",descTl:"Opisyal na nobela tungkol sa buhay at pakikipaglaban ni Saitama.",img:"https://upload.wikimedia.org/wikipedia/en/7/7c/One_Punch_Man_vol_1.jpg",link:"#"},
    {id:31,title:"Dr. Stone: Rebirth of Civilization",titleTl:"Dr. Stone: Muling Pagsilang ng Sibilisasyon",year:"2019",type:"Light Novel",lang:"EN / TL",category:["all"],desc:"Light novel telling Senku’s journey rebuilding the world with science.",descTl:"Nobela tungkol sa pagbabalik ng sibilisasyon gamit ang agham.",img:"https://upload.wikimedia.org/wikipedia/en/8/8c/Dr._Stone_vol_1.jpg",link:"#"},
    {id:32,title:"Blue Exorcist: The Movie Novel",titleTl:"Asul na Ekzorista: Nobela ng Pelikula",year:"2012",type:"Light Novel",lang:"EN / TL",category:["all"],desc:"Light novel adaptation of the Blue Exorcist movie.",descTl:"Nobela ng kwento ng pelikula ng Blue Exorcist.",img:"https://upload.wikimedia.org/wikipedia/en/7/7d/Blue_Exorcist_vol_1.jpg",link:"#"},
    {id:33,title:"Noragami: Stray God Stories",titleTl:"Noragami: Mga Kwento ng Ligaw na Diyos",year:"2013",type:"Light Novel",lang:"EN / TL",category:["all"],desc:"Light novel collection of extra stories about Yato and Hiyori.",descTl:"Mga karagdagang kwento tungkol kina Yato at Hiyori.",img:"https://upload.wikimedia.org/wikipedia/en/5/5d/Noragami_vol_1.jpg",link:"#"},
    {id:34,title:"Bungo Stray Dogs: Untold Stories",titleTl:"Mga Manunulat na Ligaw na Aso: Mga Hindi Nasabing Kwento",year:"2016",type:"Light Novel",lang:"EN / TL",category:["all"],desc:"Official light novel series expanding the detective agency missions.",descTl:"Opisyal na nobela tungkol sa mga misyon ng ahensya ng detektib.",img:"https://upload.wikimedia.org/wikipedia/en/9/9b/Bungo_Stray_Dogs_vol_1.jpg",link:"#"},
    {id:35,title:"Fire Force: The Hero's Tale",titleTl:"Puwersa ng Apoy: Kwento ng Bayani",year:"2017",type:"Light Novel",lang:"EN / TL",category:["all"],desc:"Light novel focusing on Shinra and the Special Fire Force Company 8.",descTl:"Nobela tungkol kay Shinra at sa ika-walong pangkat ng bumbero.",img:"https://upload.wikimedia.org/wikipedia/en/6/6f/Fire_Force_vol_1.jpg",link:"#"},
    {id:36,title:"Mob Psycho 100: The First Step",titleTl:"Mob Psycho 100: Ang Unang Hakbang",year:"2018",type:"Light Novel",lang:"EN / TL",category:["all"],desc:"Light novel side stories from the creator of One Punch Man.",descTl:"Karagdagang nobela mula sa lumikha ng One Punch Man.",img:"https://upload.wikimedia.org/wikipedia/en/0/0a/Mob_Psycho_100_vol_1.jpg",link:"#"},
    {id:37,title:"Vinland Saga: The True Warrior",titleTl:"Kwento ng Vinland: Ang Tunay na Mandirigma",year:"2013",type:"Light Novel",lang:"EN / TL",category:["all"],desc:"Light novel exploring Thorfinn’s journey from vengeance to peace.",descTl:"Nobela tungkol sa pagbabago ni Thorfinn mula sa paghihiganti tungo sa kapayapaan.",img:"https://upload.wikimedia.org/wikipedia/en/a/a4/Vinland_Saga_vol_1.jpg",link:"#"},
    {id:38,title:"Berserk: The Flame Dragon Knight",titleTl:"Berserk: Ang Kabalyero ng Apoy na Dragon",year:"2017",type:"Light Novel",lang:"EN / TL",category:["all"],desc:"Official light novel set in the dark fantasy world of Berserk.",descTl:"Opisyal na nobela sa madilim na mundo ng Berserk.",img:"https://upload.wikimedia.org/wikipedia/en/5/5a/Berserk_vol_1.jpg",link:"#"},
    {id:39,title:"A Silent Voice Light Novel",titleTl:"Tahimik na Tinig Nobela",year:"2014",type:"Light Novel",lang:"EN / TL",category:["all"],desc:"Original light novel about bullying, friendship, and redemption.",descTl:"Orihinal na nobela tungkol sa pagkakaibigan at pagbabago.",img:"https://upload.wikimedia.org/wikipedia/en/8/8e/A_Silent_Voice_novel.jpg",link:"#"},
    {id:40,title:"Toradora! Light Novel",titleTl:"Toradora! Nobela",year:"2006",type:"Light Novel",lang:"EN / TL",category:["all"],desc:"Classic romantic comedy light novel series.",descTl:"Sikat na nobela tungkol sa pag-ibig at pagkakaibigan.",img:"https://upload.wikimedia.org/wikipedia/en/7/7c/Toradora_vol_1.jpg",link:"#"},
    {id:41,title:"Sakura Wars: The Beginning",titleTl:"Sakura Wars: Ang Simula",year:"1996",type:"Light Novel",lang:"EN / TL",category:["all"],desc:"Light novel adaptation of the classic series.",descTl:"Nobela ng sikat na kwento ng Sakura Wars.",img:"https://upload.wikimedia.org/wikipedia/en/6/6d/Sakura_Wars_vol_1.jpg",link:"#"},
    {id:42,title:"Accel World",titleTl:"Accel World",year:"2009",type:"Light Novel",lang:"EN / TL",category:["all"],desc:"Light novel about a boy who gains speed in a virtual world.",descTl:"Nobela tungkol sa batang nagkaroon ng bilis sa mundong virtual.",img:"https://upload.wikimedia.org/wikipedia/en/7/7a/Accel_World_vol_1.jpg",link:"#"},
    {id:43,title:"Goblin Slayer",titleTl:"Tagapatay ng Goblin",year:"2016",type:"Light Novel",lang:"EN / TL",category:["all"],desc:"Original light novel about an adventurer who only hunts goblins.",descTl:"Orihinal na nobela tungkol sa mandirigma na pumapatay lamang ng mga goblin.",img:"https://upload.wikimedia.org/wikipedia/en/8/84/Goblin_Slayer_vol_1.jpg",link:"#"},
    {id:44,title:"KonoSuba: God's Blessing on This Wonderful World! Continued",titleTl:"Konosuba: Pagpapala... Karugtong",year:"2014",type:"Light Novel",lang:"EN / TL",category:["all"],desc:"Continuation of the popular comedy light novel series.",descTl:"Pagpapatuloy ng nakakatawang nobela.",img:"https://upload.wikimedia.org/wikipedia/en/e/e7/Konosuba_vol_1.jpg",link:"#"},
    {id:45,title:"Arifureta: From Commonplace to World's Strongest",titleTl:"Arifureta: Mula Karaniwan Tungo sa Pinakamalakas",year:"2015",type:"Light Novel",lang:"EN / TL",category:["all"],desc:"Light novel about an ordinary student becoming the strongest in another world.",descTl:"Nobela tungkol sa karaniwang estudyante na naging pinakamalakas sa ibang mundo.",img:"https://upload.wikimedia.org/wikipedia/en/7/7d/Arifureta_vol_1.jpg",link:"#"},
    {id:46,title:"That Time I Got Reincarnated as a Slime",titleTl:"Noong Ako ay Naging Halimaw na Dumi",year:"2014",type:"Light Novel",lang:"EN / TL",category:["trending","all"],desc:"Original light novel about a man reborn as a powerful slime monster.",descTl:"Orihinal na nobela tungkol sa lalaking naging makapangyarihang halimaw.",img:"https://upload.wikimedia.org/wikipedia/en/8/8d/That_Time_I_Got_Reincarnated_as_a_Slime_vol_1.jpg",link:"#"},
    {id:47,title:"The Rising of the Shield Hero",titleTl:"Ang Pagbangon ng Bayaning Kalasag",year:"2013",type:"Light Novel",lang:"EN / TL",category:["trending","all"],desc:"Light novel about a man summoned as one of four legendary heroes.",descTl:"Nobela tungkol sa lalaking napili bilang isa sa apat na bayani.",img:"https://upload.wikimedia.org/wikipedia/en/6/60/The_Rising_of_the_Shield_Hero_vol_1.jpg",link:"#"},
    {id:48,title:"My Youth Romantic Comedy Is Wrong, As I Expected",titleTl:"Ang Aking Kabataan ay Mali Gaya ng Inaasahan",year:"2011",type:"Light Novel",lang:"EN / TL",category:["all"],desc:"Famous school romantic comedy light novel series.",descTl:"Sikat na nobela tungkol sa buhay-pampaaralan at pag-ibig.",img:"https://upload.wikimedia.org/wikipedia/en/7/7c/My_Youth_Romantic_Comedy_Is_Wrong_As_I_Expected_vol_1.jpg",link:"#"},
    {id:49,title:"Is It Wrong to Try to Pick Up Girls in a Dungeon?",titleTl:"Mali Bang Manligaw sa Loob ng Lungga?",year:"2013",type:"Light Novel",lang:"EN / TL",category:["all"],desc:"Adventure light novel series in a fantasy city.",descTl:"Nobela ng pakikipagsapalaran sa lungsod ng pantasya.",img:"https://upload.wikimedia.org/wikipedia/en/4/45/Is_It_Wrong_to_Try_to_Pick_Up_Girls_in_a_Dungeon_vol_1.jpg",link:"#"},
    {id:50,title:"The Eminence in Shadow",titleTl:"Ang Dakilang Nasa Anino",year:"2018",type:"Light Novel",lang:"EN / TL",category:["new","all"],desc:"Light novel about a boy who hides his power and pretends to be a shadow master.",descTl:"Nobela tungkol sa batang itinatago ang lakas at nagpapanggap na pinuno ng anino.",img:"https://upload.wikimedia.org/wikipedia/en/6/67/The_Eminence_in_Shadow_vol_1.jpg",link:"#"}
];

// ==================================================
// ALL FUNCTIONS — NO MANGA, ALL EBOOKS/LIGHT NOVELS
// ==================================================
let currentLang = 'en';
const langText = {
    en: {heroTitle:"Your Favorite Anime Light Novels & Ebooks",heroDesc:"Download thousands of anime light novels and ebooks for free",trendingTitle:"🔥 Trending Now",newTitle:"✨ New Released",allTitle:"📚 All Anime Ebooks",searchPlaceholder:"Search anime ebooks..."},
    tl: {heroTitle:"Ang Iyong Mga Paboritong Nobela at Ebook",heroDesc:"Mag-download ng libo-libong anime nobela at ebook nang libre",trendingTitle:"🔥 Pinakasikat Ngayon",newTitle:"✨ Mga Bagong Labas",allTitle:"📚 Lahat ng Anime Ebook",searchPlaceholder:"Maghanap ng anime ebook..."}
};

const navbar = document.querySelector('.navbar');
const langSelect = document.getElementById('langSelect');
const searchInput = document.getElementById('searchInput');
const infoModal = document.getElementById('infoModal');
const closeBtn = document.querySelector('.close-btn');
const downloadBtn = document.getElementById('downloadBtn');

window.addEventListener('scroll', () => navbar.classList.toggle('scrolled', window.scrollY > 50));

langSelect.addEventListener('change', e => {
    currentLang = e.target.value;
    updateLanguage();
    renderCards();
});

function updateLanguage() {
    document.getElementById('heroTitle').innerText = langText[currentLang].heroTitle;
    document.getElementById('heroDesc').innerText = langText[currentLang].heroDesc;
    document.getElementById('trendingTitle').innerText = langText[currentLang].trendingTitle;
    document.getElementById('newTitle').innerText = langText[currentLang].newTitle;
    document.getElementById('allTitle').innerText = langText[currentLang].allTitle;
    searchInput.placeholder = langText[currentLang].searchPlaceholder;
}

function renderCards(data = animeData) {
    document.getElementById('trendingRow').innerHTML = '';
    document.getElementById('newRow').innerHTML = '';
    document.getElementById('allRow').innerHTML = '';
    data.forEach(anime => {
        const card = document.createElement('div');
        card.className = 'anime-card';
        card.innerHTML = `<img src="${anime.img}" alt="${currentLang==='en'?anime.title:anime.titleTl}" loading="lazy"><div class="card-info"><h3>${currentLang==='en'?anime.title:anime.titleTl}</h3><p>${anime.year} • ${anime.type}</p></div>`;
        card.addEventListener('click', () => openModal(anime));
        if (anime.category.includes('trending')) document.getElementById('trendingRow').appendChild(card);
        if (anime.category.includes('new')) document.getElementById('newRow').appendChild(card);
        if (anime.category.includes('all')) document.getElementById('allRow').appendChild(card);
    });
}

function openModal(anime) {
    document.getElementById('modalImg').src = anime.img;
    document.getElementById('modalTitle').innerText = currentLang==='en'?anime.title:anime.titleTl;
    document.getElementById('modalYear').innerText = anime.year;
    document.getElementById('modalType').innerText = anime.type;
    document.getElementById('modalLang').innerText = anime.lang;
    document.getElementById('modalDesc').innerText = currentLang==='en'?anime.desc:anime.descTl;
    downloadBtn.onclick = () => window.open(anime.link, '_blank');
    infoModal.classList.add('active');
    document.body.style.overflow = 'hidden';
}

closeBtn.addEventListener('click', () => { infoModal.classList.remove('active'); document.body.style.overflow='auto'; });
window.addEventListener('click', e => { if(e.target===infoModal){ infoModal.classList.remove('active'); document.body.style.overflow='auto'; }});
searchInput.addEventListener('input', e => { const kw=e.target.value.toLowerCase().trim(); renderCards(kw?animeData.filter(a=>a.title.toLowerCase().includes(kw)||a.titleTl.toLowerCase().includes(kw)):animeData); });

renderCards();
updateLanguage();
